#!/usr/bin/env ruby

Signal.trap('INT') { exit 1 }

require 'pathname'
exe = Pathname.new(__FILE__).realpath

$LOAD_PATH.unshift File.expand_path('../../lib', exe)
require 'etfc/cli'

ETFC::CLI.start(ARGV)
